// SSR demo: the module behind the README hero GIF (see ../demo-gif/README.md).
//
// The story it tells in one screen: `renderToString` is slow, and the cost splits three ways --
// react-dom's reconciler, the styling library resolving class conflicts, and your own component --
// each attributed down to a source line by `wpd query cpu`.
//
// Why it looks like this:
//   - No JSX, so there is NO build step. `createElement` reads worse than JSX but means the
//     demo runs straight from source. The GIF previously rendered from a pre-compiled bundle in a
//     private repo, so it could not be regenerated by anyone else and silently rotted until it was
//     demonstrating a flag that no longer existed.
//   - tailwind-merge is a RUNTIME library, so its cost shows up in a sampling profile. A
//     compile-time CSS-in-JS library (next-yak, Linaria) would have nothing left to sample, which
//     is exactly why those need profiling from their compiled output instead.
//   - Dependencies stay external (a plain `npm install` here, never bundled in), because that is
//     what lets wpd roll self-time up per package. Bundle react-dom in and its cost lands in your
//     `app` bucket.
//
// Run:  cd examples/ssr-demo && npm install
//       node ../../dist/cli.js record examples/ssr-demo/demo.mjs --target node --iterations 80
//       node ../../dist/cli.js query cpu latest --top 5
import { createElement } from "react";
import { renderToString } from "react-dom/server";
import { twMerge } from "tailwind-merge";

const VARIANTS = {
  primary: "bg-blue-500 text-white hover:bg-blue-600 px-4 py-2",
  danger: "bg-red-500 text-white hover:bg-red-600 px-4 py-2",
  ghost: "bg-transparent text-slate-700 hover:bg-slate-100 px-4 py-2",
};
const SIZES = {
  sm: "px-2 py-1 text-sm",
  md: "px-4 py-2 text-base",
  lg: "px-6 py-3 text-lg",
};

/**
 * The `app` bucket. twMerge resolves the conflicts between the variant, size and caller classes
 * (all three set padding utilities), which is the whole reason a styling library costs anything
 * at render time.
 */
function Button({ variant, size, className, children }) {
  const classes = twMerge("rounded font-medium", VARIANTS[variant], SIZES[size], className);
  return createElement("button", { className: classes, type: "button" }, children);
}

function Row({ index }) {
  const variants = Object.keys(VARIANTS);
  const sizes = Object.keys(SIZES);
  return createElement(
    "div",
    { className: "flex gap-2" },
    variants.map((variant, column) =>
      createElement(
        Button,
        {
          key: variant,
          variant,
          size: sizes[(index + column) % sizes.length],
          // a caller override that conflicts with the variant, so twMerge has real work to do
          className: column % 2 ? "px-8 shadow-sm" : "py-4",
        },
        `Action ${index}-${column}`,
      ),
    ),
  );
}

function Page() {
  return createElement(
    "main",
    { className: "p-8" },
    Array.from({ length: 400 }, (_, index) => createElement(Row, { key: index, index })),
  );
}

export function run() {
  renderToString(createElement(Page));
}
